/** Hebrew display labels for strings that come straight out of data extraction. Exact-match dictionaries; anything missing falls through to the original text. */

export const METRIC_HE: Record<string, string> = {
  future_profit_opening: 'רווח עתידי גלום בפוליסות חיסכון: יתרת פתיחה (לא CSM)', future_profit_closing: 'רווח עתידי גלום בפוליסות חיסכון: יתרת סגירה (לא CSM)', future_profit_new_business: 'רווח עתידי גלום בפוליסות חיסכון: עסק חדש (לא CSM)',
  future_profit_release: 'רווח עתידי גלום בפוליסות חיסכון: שחרור (לא CSM)', future_profit_economic_interest_and_other_effects: 'רווח עתידי גלום בפוליסות חיסכון: ריבית והשפעות כלכליות אחרות (לא CSM)',
  future_profit_special_events: 'רווח עתידי גלום בפוליסות חיסכון: אירועים מיוחדים (לא CSM)', 'future_profit_subtotal:balances before release': 'רווח עתידי גלום בפוליסות חיסכון: סכום ביניים לפני שחרור (לא CSM)', future_profit_subtotal: 'רווח עתידי גלום בפוליסות חיסכון: סכום ביניים (לא CSM)',
  comprehensive_income_before_tax: 'רווח כולל לפני מס', insurance_service_result: 'תוצאות שירותי ביטוח', csm_closing: 'CSM: יתרת סגירה', csm_expected_release: 'שחרור CSM צפוי',
  insurance_revenue: 'הכנסות משירותי ביטוח', management_fees: 'דמי ניהול', net_investment_and_finance_result: 'תוצאות השקעה ומימון, נטו', csm_release: 'CSM: שחרור לרווח',
  gross_written_premiums: 'פרמיות ברוטו', risk_adjustment: 'התאמת סיכון (RA)', csm_opening: 'CSM: יתרת פתיחה', losses_on_onerous_contracts: 'הפסדים מחוזים מכבידים',
  rev_ra_release: 'הכנסות: שחרור RA', csm_changes_in_estimates: 'CSM: שינויי אומדן', new_business_annualized_premiums: 'פרמיה משונתת, עסק חדש', sensitivity: 'רגישות',
  pension_gemel_profit_before_tax: 'רווח לפני מס, פנסיה וגמל', csm_interest_accretion: 'CSM: צבירת ריבית', combined_ratio: 'Combined ratio', csm_new_business: 'CSM: עסק חדש',
  insurance_finance_result: 'הכנסות (הוצאות) מימון ביטוח', rev_csm_release: 'הכנסות: שחרור CSM', discount_rate: 'שיעור היוון', reins_expense_csm_release: 'ביטוח משנה: שחרור CSM',
  rev_paa: 'הכנסות: PAA', loss_component: 'רכיב הפסד', solvency_surplus: 'עודף הון', csm_subtotal: 'CSM: סכום ביניים', total_assets: 'סך נכסים',
  rev_expected_claims_and_expenses: 'הכנסות: תביעות והוצאות צפויות', profit_attributable: 'רווח נקי לבעלי המניות', comprehensive_income_attributable: 'רווח כולל לבעלי המניות',
  ra_closing: 'RA: יתרת סגירה', profit_before_tax: 'רווח לפני מס', rev_acquisition_cashflow_recovery: 'הכנסות: השבת תזרימי רכישה', insurance_finance_component: 'רכיב מימון ביטוח',
  reins_expense_ra_release: 'ביטוח משנה: שחרור RA', roe_reported: 'תשואה להון, כפי שדווחה', dividend_declared: 'דיבידנד שהוכרז', solvency_ratio_with_transitional: 'יחס כושר פירעון, עם הוראות מעבר',
  dividend_paid: 'דיבידנד ששולם', own_funds: 'הון עצמי לעניין SCR', solvency_ratio_without_transitional: 'יחס כושר פירעון, ללא הוראות מעבר', equity_attributable: 'הון לבעלי המניות',
  rev_other: 'הכנסות: אחר', csm_other: 'CSM: אחר', scr: 'הון נדרש (SCR)', ra_opening: 'RA: יתרת פתיחה', aum_total: 'נכסים מנוהלים, סך הכול', mcr: 'סף הון (MCR)',
  ra_release: 'RA: שחרור', target_solvency_ratio: 'יעד יחס כושר פירעון', csm_economic_interest_and_other_effects: 'CSM: ריבית והשפעות כלכליות אחרות', assumption_update: 'עדכון הנחות',
  rev_non_paa_total: 'הכנסות: סך חוזים ללא PAA', income_before_tax: 'רווח לפני מס', core_income: 'רווח ליבה', dividend_declared_after_period: 'דיבידנד שהוכרז לאחר תאריך המאזן',
  aum_pension: 'נכסים מנוהלים: פנסיה', solvency_surplus_without_transitional: 'עודף הון, ללא הוראות מעבר', net_reinsurance_result: 'תוצאות ביטוח משנה, נטו',
  operating_profit_before_tax: 'רווח תפעולי לפני מס', note17d_csm_new_business: 'CSM: עסק חדש (ביאור 17ד)', insurance_finance_accrued_interest: 'מימון ביטוח: צבירת ריבית',
  insurance_service_expenses: 'הוצאות שירותי ביטוח', insurance_finance_interest_accrued: 'מימון ביטוח: ריבית שנצברה', contributions: 'הפקדות',
  note10_csm_effect_demographic_and_other: 'השפעה על CSM: הנחות דמוגרפיות ואחרות (ביאור 10)', note13_pl_effect_interest_rate_and_yield: 'השפעה על רווח והפסד: ריבית ותשואה (ביאור 13)',
  comprehensive_income_before_tax_after_allocation: 'רווח כולל לפני מס, לאחר הקצאה', insurance_finance_rate_effect: 'מימון ביטוח: השפעת שינויי ריבית',
  solvency_ratio_without_transitional_after_capital_actions: 'יחס כושר פירעון, ללא הוראות מעבר, לאחר פעולות הון', comprehensive_income_total: 'רווח כולל',
  own_funds_with_transitional: 'הון עצמי לעניין SCR, עם הוראות מעבר', scr_with_transitional: 'הון נדרש (SCR), עם הוראות מעבר',
  solvency_ratio_with_transitional_after_capital_actions: 'יחס כושר פירעון, עם הוראות מעבר, לאחר פעולות הון', management_fees_fixed: 'דמי ניהול קבועים', total_equity: 'סך הון',
  own_funds_mcr: 'הון עצמי לעניין MCR', total_investment_gains_recognized_in_income_statement: 'סך רווחי השקעות שהוכרו בדוח רווח והפסד', net_investment_and_finance_result_pl: 'תוצאות השקעה ומימון, נטו (רווח והפסד)',
  insurance_service_expense: 'הוצאות שירותי ביטוח', insurance_service_result_before_reinsurance: 'תוצאות שירותי ביטוח לפני ביטוח משנה', net_investment_result_oci: 'תוצאות השקעה, נטו (רווח כולל אחר)',
  assumption_change_effect: 'השפעת שינוי הנחות', roe_reported_ex_adjustments: 'תשואה להון, כפי שדווחה, ללא התאמות', aum_gemel: 'נכסים מנוהלים: גמל',
  solvency_surplus_after_capital_actions: 'עודף הון, לאחר פעולות הון', note13_csm_effect_interest_rate_and_yield: 'השפעה על CSM: ריבית ותשואה (ביאור 13)',
  note13_csm_effect_demographic_and_other: 'השפעה על CSM: הנחות דמוגרפיות ואחרות (ביאור 13)', note13_pl_effect_demographic_and_other: 'השפעה על רווח והפסד: הנחות דמוגרפיות ואחרות (ביאור 13)',
  csm_special_events: 'CSM: אירועים מיוחדים', own_funds_for_mcr: 'הון עצמי לעניין MCR', ise_claims_incurred: 'הוצאות שירותי ביטוח: תביעות שהתהוו', ise_past_service: 'הוצאות שירותי ביטוח: שירות עבר',
  ise_amortization_acquisition: 'הוצאות שירותי ביטוח: הפחתת עלויות רכישה', ise_total: 'הוצאות שירותי ביטוח, סך הכול', reinsurance_expenses_total: 'הוצאות ביטוח משנה, סך הכול',
  reinsurance_recoveries_claims: 'ביטוח משנה: השבות בגין תביעות', reinsurance_past_service: 'ביטוח משנה: שירות עבר', reinsurance_revenues_total: 'הכנסות ביטוח משנה, סך הכול',
  reinsurance_net_result: 'תוצאות ביטוח משנה, נטו', solvency_surplus_over_target: 'עודף מעל היעד', note17d_losses_on_onerous_contracts: 'הפסדים מחוזים מכבידים (ביאור 17ד)',
  new_business_one_off_premiums: 'פרמיות חד פעמיות, עסק חדש', sensitivity_exposed_balance: 'רגישות: יתרה חשופה', insurance_finance_rate_effects: 'מימון ביטוח: השפעת שינויי ריבית',
  reinsurance_expenses: 'הוצאות ביטוח משנה', reinsurance_revenues: 'הכנסות ביטוח משנה', management_fees_variable: 'דמי ניהול משתנים', investment_contract_receipts: 'תקבולים בגין חוזי השקעה',
  target_solvency_ratio_board: 'יעד יחס כושר פירעון (דירקטוריון)', target_solvency_ratio_min_with_transitional: 'יעד יחס כושר פירעון מינימלי, עם הוראות מעבר', solvency_surplus_with_transitional: 'עודף הון, עם הוראות מעבר',
  excess_capital_over_target: 'עודף הון מעל היעד', investment_gains_assets_held_against_insurance_and_yield_dependent: 'רווחי השקעה בנכסים כנגד התחייבויות ביטוח ותלויות תשואה',
  own_funds_without_transitional: 'הון עצמי לעניין SCR, ללא הוראות מעבר', scr_without_transitional: 'הון נדרש (SCR), ללא הוראות מעבר',
  note10_csm_effect_interest_and_financial_assumptions: 'השפעה על CSM: ריבית והנחות פיננסיות (ביאור 10)', note13_csm_impact_demographic_and_other_assumptions: 'השפעה על CSM: הנחות דמוגרפיות ואחרות (ביאור 13)',
  target_dividend_payout: 'יעד שיעור חלוקת דיבידנד', net_profit: 'רווח נקי', note10_csm_effect_total: 'השפעה על CSM, סך הכול (ביאור 10)', profit_for_period: 'רווח לתקופה',
  note13_csm_impact_discount_rate_and_expected_return: 'השפעה על CSM: שיעור היוון ותשואה צפויה (ביאור 13)', note13_assumption_update_finance_effect: 'עדכון הנחות: השפעה פיננסית (ביאור 13)',
  target_max_cet1_ratio: 'יעד יחס CET1 מרבי', target_max_total_capital_ratio: 'יעד יחס הון כולל מרבי', target_solvency_ratio_min_without_transitional: 'יעד יחס כושר פירעון מינימלי, ללא הוראות מעבר',
  receipts_investment_contracts: 'תקבולים בגין חוזי השקעה', reinsurance_recoveries_losses: 'ביטוח משנה: השבות בגין הפסדים', yield_component_investment_contracts: 'רכיב תשואה בחוזי השקעה',
  contributions_towards_benefits: 'הפקדות לצורך הטבות', own_funds_after_capital_transactions: 'הון עצמי לעניין SCR, לאחר פעולות הון', solvency_surplus_after_capital_transactions: 'עודף הון, לאחר פעולות הון',
  note17d_gain_on_initial_recognition_reinsurance: 'רווח מהכרה לראשונה בביטוח משנה (ביאור 17ד)', capital_raising_after_calculation_date: 'גיוס הון לאחר תאריך החישוב',
  own_funds_after_capital_events: 'הון עצמי לעניין SCR, לאחר אירועי הון', solvency_surplus_after_capital_events: 'עודף הון, לאחר אירועי הון', adjusted_profit_after_tax: 'רווח מותאם לאחר מס',
  own_funds_after_capital_actions: 'הון עצמי לעניין SCR, לאחר פעולות הון', adjusted_profit_before_tax: 'רווח מותאם לפני מס', target_dividend_payout_min: 'יעד שיעור חלוקת דיבידנד מינימלי',
  target_total_payout_min: 'יעד שיעור חלוקה כולל מינימלי', profit_total: 'רווח, סך הכול', investment_contracts_receipts: 'תקבולים בגין חוזי השקעה', target_solvency_ratio_minimum: 'יעד יחס כושר פירעון מינימלי',
  capital_issuance_after_calculation_date: 'הנפקת הון לאחר תאריך החישוב', solvency_surplus_vs_board_target: 'עודף הון מעל יעד הדירקטוריון', solvency_surplus_vs_target: 'עודף מעל היעד',
  target_solvency_surplus_vs_board_target_without_transitional: 'יעד: עודף הון מעל יעד הדירקטוריון, ללא הוראות מעבר', equity_total: 'סך הון', total_capital_ratio: 'יחס הון כולל', cet1_ratio: 'יחס CET1',
  note13_assumption_update_csm_effect: 'עדכון הנחות: השפעה על CSM (ביאור 13)', solvency_ratio: 'יחס כושר פירעון', solvency_ratio_after_capital_actions: 'יחס כושר פירעון, לאחר פעולות הון',
  roe_core: 'תשואה להון, ליבה', excess_financial_spread: 'מרווח פיננסי עודף', profit_for_year: 'רווח לשנה', income_tax_on_comprehensive_income: 'מס על הכנסה כוללת',
  one_time_premium_new_business: 'פרמיות חד פעמיות, עסק חדש', solvency_ratio_with_transitional_after_capital_transactions: 'יחס כושר פירעון, עם הוראות מעבר, לאחר פעולות הון',
  solvency_ratio_without_transitional_after_capital_transactions: 'יחס כושר פירעון, ללא הוראות מעבר, לאחר פעולות הון', target_dividend_payout_pct_of_comprehensive_income: 'יעד שיעור חלוקת דיבידנד מהרווח הכולל',
  net_income: 'רווח נקי', investment_contract_proceeds: 'תקבולים בגין חוזי השקעה', solvency_ratio_without_transitional_after_capital_events: 'יחס כושר פירעון, ללא הוראות מעבר, לאחר אירועי הון',
  solvency_ratio_with_transitional_after_capital_events: 'יחס כושר פירעון, עם הוראות מעבר, לאחר אירועי הון', core_profit: 'רווח ליבה', contributions_pension: 'הפקדות: פנסיה', contributions_gemel: 'הפקדות: גמל',
  aum_financial_services: 'נכסים מנוהלים: שירותים פיננסיים', surplus_vs_target: 'עודף מעל היעד', ra_confidence_level: 'RA: רמת ביטחון', proceeds_investment_contracts: 'תקבולים בגין חוזי השקעה',
  own_funds_with_transitional_pro_forma: 'הון עצמי לעניין SCR, עם הוראות מעבר, פרו פורמה', solvency_surplus_pro_forma: 'עודף הון, פרו פורמה', solvency_ratio_with_transitional_pro_forma: 'יחס כושר פירעון, עם הוראות מעבר, פרו פורמה',
  own_funds_without_transitional_pro_forma: 'הון עצמי לעניין SCR, ללא הוראות מעבר, פרו פורמה', solvency_surplus_without_transitional_pro_forma: 'עודף הון, ללא הוראות מעבר, פרו פורמה',
  solvency_ratio_without_transitional_pro_forma: 'יחס כושר פירעון, ללא הוראות מעבר, פרו פורמה', target_excess_capital: 'יעד: עודף הון', roe_adjusted: 'תשואה להון מותאמת',
  target_dividend_threshold_with_transitional: 'סף לחלוקת דיבידנד, עם הוראות מעבר', solvency_ratio_without_transitional_after_capital_raise: 'יחס כושר פירעון, ללא הוראות מעבר, לאחר גיוס הון',
  solvency_ratio_with_transitional_after_capital_raise: 'יחס כושר פירעון, עם הוראות מעבר, לאחר גיוס הון', solvency_surplus_with_transitional_after_capital_actions: 'עודף הון, עם הוראות מעבר, לאחר פעולות הון',
  own_funds_after_capital_actions_without_transitional: 'הון עצמי לעניין SCR, לאחר פעולות הון, ללא הוראות מעבר', solvency_surplus_after_capital_actions_without_transitional: 'עודף הון, לאחר פעולות הון, ללא הוראות מעבר',
  own_funds_after_capital_actions_with_transitional: 'הון עצמי לעניין SCR, לאחר פעולות הון, עם הוראות מעבר', solvency_surplus_after_capital_actions_with_transitional: 'עודף הון, לאחר פעולות הון, עם הוראות מעבר',
  pres23_csm_new_business: 'CSM: עסק חדש (מצגת)', target_solvency_ratio_min_stability: 'יעד יחס כושר פירעון מינימלי (יציבות)', target_solvency_ratio_minimum_end_2032: 'יעד יחס כושר פירעון מינימלי לסוף 2032',
  target_solvency_dividend_threshold: 'סף כושר פירעון לחלוקת דיבידנד', target_share_buyback_2026: 'יעד רכישה עצמית של מניות, 2026', aum_total_nostro: 'נכסים מנוהלים: נוסטרו', aum_total_members_funds: 'נכסים מנוהלים: כספי חברים',
  aum_pension_gemel: 'נכסים מנוהלים: פנסיה וגמל', target_solvency_ratio_dividend_threshold_with_tmtp: 'סף כושר פירעון לחלוקת דיבידנד, עם הוראות מעבר', target_solvency_ratio_dividend_threshold_without_tmtp: 'סף כושר פירעון לחלוקת דיבידנד, ללא הוראות מעבר',
  aum_insurance_and_investment_contracts: 'נכסים מנוהלים: ביטוח ופוליסות חיסכון (חוזי השקעה)', aum_hmo_ltc: 'נכסים מנוהלים: קרנות סיעוד של קופות החולים', aum_credit: 'נכסים מנוהלים: אשראי', aum_nostro: 'נכסי נוסטרו',
  target_dividend_threshold_solvency: 'סף כושר פירעון לחלוקת דיבידנד', target_csm_growth_from_variable_fees: 'יעד צמיחת CSM מדמי ניהול משתנים', target_nostro_portfolio: 'יעד תיק נוסטרו',
  target_solvency_ratio_with_transitional_minimum: 'יעד יחס כושר פירעון מינימלי, עם הוראות מעבר', note13_csm_change_since_dec2024: 'שינוי ב-CSM מאז דצמבר 2024 (ביאור 13)', target_core_income: 'יעד רווח ליבה',
  transitional_deduction: 'ניכוי הוראות מעבר',
};

/** Free text after "family:" (case-sensitive exact match). */
export const TEXT_HE: Record<string, string> = {
  'Total changes in the income statement and other comprehensive income': 'סך השינויים ברווח והפסד וברווח כולל אחר',
  'Total income from insurance services': 'סך הכנסות משירותי ביטוח',
  'Interest accrued': 'ריבית שנצברה',
  'Effects of changes in interest rates and other financial assumptions (including inflation)': 'השפעת שינויים בשיעורי ריבית ובהנחות פיננסיות אחרות (כולל אינפלציה)',
  'Effect of difference between current-rate and original-rate discounting of changes in FCF charged to CSM': 'השפעת ההפרש בין היוון בשיעור נוכחי להיוון בשיעור מקורי של שינויים בתזרימי המזומנים העתידיים שנזקפו ל-CSM',
  'Effects of changes in interest rates and other financial assumptions': 'השפעת שינויים בשיעורי ריבית ובהנחות פיננסיות אחרות',
  'Effect of difference between current and original discount rate on changes in FCF carried to CSM': 'השפעת ההפרש בין שיעור ההיוון הנוכחי למקורי על שינויים בתזרימי המזומנים העתידיים שנזקפו ל-CSM',
  'Change in liabilities arising from changes in fair value of underlying items of VFA contracts': 'שינוי בהתחייבויות הנובע משינוי בשווי ההוגן של הפריטים הבסיסיים בחוזי VFA',
  'Change in liabilities from changes in fair value of underlying items of VFA contracts': 'שינוי בהתחייבויות הנובע משינוי בשווי ההוגן של הפריטים הבסיסיים בחוזי VFA',
  'Effects of the risk mitigation option for VFA contracts': 'השפעת אפשרות הפחתת הסיכון בחוזי VFA',
  'Exchange rate differences and other, net': 'הפרשי שער ואחר, נטו',
  'Total revenues (expenses), net for reinsurance contracts held': 'סך הכנסות (הוצאות), נטו, מחוזי ביטוח משנה שנרכשו',
  'balances before release': 'יתרות לפני שחרור',
  'Morbidity rate 5% increase': 'שיעור תחלואה, עלייה של 5%', 'Morbidity rate 5% decrease': 'שיעור תחלואה, ירידה של 5%',
  'Mortality rate 5% increase': 'שיעור תמותה, עלייה של 5%', 'Mortality rate 5% decrease': 'שיעור תמותה, ירידה של 5%',
  'Morbidity rate Decrease of 5%': 'שיעור תחלואה, ירידה של 5%', 'Mortality rate Decrease of 5%': 'שיעור תמותה, ירידה של 5%',
  'Morbidity rate decrease of 5%': 'שיעור תחלואה, ירידה של 5%', 'Mortality rate decrease of 5%': 'שיעור תמותה, ירידה של 5%',
  'morbidity +5%': 'שיעור תחלואה, עלייה של 5%', 'morbidity -5%': 'שיעור תחלואה, ירידה של 5%', 'mortality +5%': 'שיעור תמותה, עלייה של 5%', 'mortality -5%': 'שיעור תמותה, ירידה של 5%',
  'morbidity rate +5%': 'שיעור תחלואה, עלייה של 5%', 'morbidity rate -5%': 'שיעור תחלואה, ירידה של 5%',
  'mortality rate +5% (first mortality column)': 'שיעור תמותה, עלייה של 5% (עמודת תמותה ראשונה)',
  'interest rate +0.5pp': 'שיעור ריבית, עלייה של 0.5 נקודות אחוז', 'interest rate -0.5pp': 'שיעור ריבית, ירידה של 0.5 נקודות אחוז',
  'interest rate +0.5%': 'שיעור ריבית, עלייה של 0.5 נקודות אחוז', 'interest rate -0.5%': 'שיעור ריבית, ירידה של 0.5 נקודות אחוז',
  'Interest rate increase of 0.5 percentage points': 'שיעור ריבית, עלייה של 0.5 נקודות אחוז', 'Interest rate decrease of 0.5 percentage points': 'שיעור ריבית, ירידה של 0.5 נקודות אחוז',
  'equity price +10%': 'מחיר מניות, עלייה של 10%', 'equity price -10%': 'מחיר מניות, ירידה של 10%',
  'investments in equity instruments +10%': 'השקעות במכשירים הוניים, עלייה של 10%', 'investments in equity instruments -10%': 'השקעות במכשירים הוניים, ירידה של 10%',
  'Share price 10% increase': 'מחיר מניות, עלייה של 10%', 'Share price 10% decrease': 'מחיר מניות, ירידה של 10%',
  'Share rate 10% increase': 'מחיר מניות, עלייה של 10%', 'Share rate decrease of 10%': 'מחיר מניות, ירידה של 10%',
  'Interest rate: net exposure to higher interest rate An increase of 0.5 percentage points': 'ריבית: חשיפה נטו לעליית ריבית, עלייה של 0.5 נקודות אחוז',
  'Interest rate: net exposure to interest rate reductions A decrease of 0.5 percentage points': 'ריבית: חשיפה נטו לירידת ריבית, ירידה של 0.5 נקודות אחוז',
  'Share price: net exposure to increase in share price 10% increase': 'מחיר מניות: חשיפה נטו לעליית מחיר, עלייה של 10%',
  'Share price: net exposure to decrease in share price Decrease of 10%': 'מחיר מניות: חשיפה נטו לירידת מחיר, ירידה של 10%',
  'Interest rate: net exposure to higher interest rate': 'ריבית: חשיפה נטו לעליית ריבית', 'Interest rate: net exposure to interest rate reductions': 'ריבית: חשיפה נטו לירידת ריבית',
  'Share price: net exposure to increase in share price': 'מחיר מניות: חשיפה נטו לעליית מחיר', 'Share price: net exposure to decrease in share price': 'מחיר מניות: חשיפה נטו לירידת מחיר',
  'Morbidity rate': 'שיעור תחלואה', 'Mortality rate': 'שיעור תמותה',
  'Changes in reinsurance CSM': 'שינויים ב-CSM ביטוח משנה',
  'Changes in recoveries of losses for groups of onerous underlying insurance contracts adjusting the CSM': 'שינויים בהשבת הפסדים בגין קבוצות חוזי ביטוח בסיסיים מכבידים המתאימים את ה-CSM',
  'Changes in recoveries of losses for groups of onerous underlying insurance contracts adjusting the contractual service margin': 'שינויים בהשבת הפסדים בגין קבוצות חוזי ביטוח בסיסיים מכבידים המתאימים את ה-CSM',
  'Changes in estimates of losses (reversal of losses) for groups of onerous underlying insurance contracts': 'שינויים באומדני הפסדים (ביטול הפסדים) בגין קבוצות חוזי ביטוח בסיסיים מכבידים',
  'Actual vs. expected financial spread, including modified assumptions': 'מרווח פיננסי בפועל מול צפוי, כולל הנחות שעודכנו',
  'time value (interest accretion) and other financial variables': 'ערך הזמן (צבירת ריבית) ומשתנים פיננסיים אחרים',
  'Balance of liabilities as of January 1': 'יתרת התחייבויות ליום 1 בינואר', 'Balance of assets as of January 1': 'יתרת נכסים ליום 1 בינואר',
  'Balance of assets as of December 31': 'יתרת נכסים ליום 31 בדצמבר', 'Balance of liabilities as of December 31': 'יתרת התחייבויות ליום 31 בדצמבר',
  'Note 21E effect of revision of estimates': 'השפעת עדכון אומדנים (ביאור 21ה)',
  'Other adjustments': 'התאמות אחרות', 'other': 'אחר',
  'Experience adjustments arising from premiums received': 'תיאומים בהתאם לניסיון הנובעים מפרמיות שהתקבלו',
  'Experience adjustments arising from premiums paid': 'תיאומים בהתאם לניסיון הנובעים מפרמיות ששולמו',
  'Experience adjustments from premiums received in the period relating to current or past service': 'תיאומים בהתאם לניסיון מפרמיות שהתקבלו בתקופה ומתייחסות לשירות שוטף או עבר',
  'Total contracts for which the PAA was not applied': 'סך חוזים שלגביהם לא יושמה גישת הקצאת הפרמיה (PAA)',
  'income (loss) from investments and finance, net': 'הכנסות (הפסדים) מהשקעות ומימון, נטו', 'income from insurance services': 'הכנסות משירותי ביטוח',
  'VAT rate update': 'עדכון שיעור מע"מ', 'mortality tables': 'לוחות תמותה', 'lapse assumption study': 'מחקר הנחת ביטולים', 'retirement age': 'גיל פרישה',
  'morbidity rate': 'שיעור תחלואה', 'lapse rate': 'שיעור ביטולים', 'risk adjustment (RA)': 'התאמת סיכון (RA)',
};

/** Sub-segment strings as reported (exact match). */
export const SEGMENT_HE: Record<string, string> = {
  life_health: 'חיים ובריאות', pc_wesure: 'ווישור (כללי)', clal_insurance: 'כלל ביטוח', 'life+health+pc': 'חיים, בריאות וכללי', provident: 'גמל', life_insurance: 'ביטוח חיים',
  phoenix_insurance: 'הפניקס ביטוח', harel_insurance: 'הראל ביטוח', financial_services: 'שירותים פיננסיים', pc_ayalon: 'איילון (כללי)', 'Menora Insurance': 'מנורה ביטוח',
  'Life Insurance and Long-Term Savings': 'ביטוח חיים וחיסכון ארוך טווח', 'Health Insurance': 'ביטוח בריאות', pension: 'פנסיה', investment_contracts: 'פוליסות חיסכון (חוזי השקעה)',
  'Long-Term Savings': 'חיסכון ארוך טווח', 'Life and Health Risks': 'סיכוני חיים ובריאות', 'Shomera Insurance': 'שומרה ביטוח', 'P&C Insurance': 'ביטוח כללי', 'Non-segmented': 'לא מיוחס למגזרים',
  adjustments: 'התאמות וקיזוזים', credit_cards: 'כרטיסי אשראי', 'Phoenix Insurance': 'הפניקס ביטוח', 'Wealth & Investments': 'עושר והשקעות', overseas_insurance: 'ביטוח בחו"ל',
  insurer_subsidiary: 'חברת הביטוח', Pension: 'פנסיה', Provident: 'גמל', gemel: 'גמל', pc_incl_overseas: 'כללי כולל חו"ל', 'Compulsory Motor': 'רכב חובה', 'Motor Property': 'רכב רכוש',
  life_and_health: 'חיים ובריאות', 'Investment contracts': 'פוליסות חיסכון (חוזי השקעה)', 'Investment policies': 'פוליסות חיסכון (חוזי השקעה)', 'pc:איילון': 'כללי: איילון', life_investment_contracts: 'פוליסות חיסכון (חוזי השקעה)',
  clal_insurance_without_transitional: 'כלל ביטוח, ללא הוראות מעבר', credit: 'אשראי', 'insurer:מגדל ביטוח': 'מגדל ביטוח', phoenix_insurance_without_transitional: 'הפניקס ביטוח, ללא הוראות מעבר',
  'pc:ווישור': 'כללי: ווישור', pc_motor_property: 'כללי: רכב רכוש', ayalon_insurance: 'איילון ביטוח', 'life+health': 'חיים ובריאות', Credit: 'אשראי', unallocated: 'לא מיוחס',
  'Adjustments and offsets': 'התאמות וקיזוזים', pc_ayalon_motor_property: 'איילון (כללי): רכב רכוש', pc_wesure_motor_property: 'ווישור (כללי): רכב רכוש', 'רכב רכוש': 'רכב רכוש',
  non_segmented: 'לא מיוחס למגזרים', agencies_other: 'סוכנויות ואחר', pension_funds: 'קרנות פנסיה', provident_funds: 'קופות גמל', 'Life and Health Segments': 'מגזרי חיים ובריאות',
  'Health - Growth': 'בריאות: צמיחה', 'Health - Run-off': 'בריאות: ראן-אוף', 'Life - Growth': 'חיים: צמיחה', 'Life - Run-off': 'חיים: ראן-אוף', overseas: 'חו"ל', insurance_companies_overseas: 'חברות ביטוח בחו"ל',
  'Life Insurance and Long-Term Savings - Policies with a yield-dependent savings component': 'חיים וחיסכון ארוך טווח: פוליסות הכוללות רכיב חיסכון תלוי תשואה (ביטוחי מנהלים)',
  'Life Insurance and Long-Term Savings - Policies with a non-yield-dependent savings component': 'חיים וחיסכון ארוך טווח: פוליסות הכוללות רכיב חיסכון שאינו תלוי תשואה (ביטוחי מנהלים)',
  'Life Insurance and Long-Term Savings - Policies without a savings component': 'חיים וחיסכון ארוך טווח: פוליסות ללא רכיב חיסכון',
  'Life Insurance and Long-Term Savings - Investment contracts': 'חיים וחיסכון ארוך טווח: פוליסות חיסכון (חוזי השקעה)',
  'Life Insurance and Long-Term Savings - Provident': 'חיים וחיסכון ארוך טווח: גמל', 'Life Insurance and Long-Term Savings - Pension': 'חיים וחיסכון ארוך טווח: פנסיה',
  'Life Insurance and Long-Term Savings - Life Insurance': 'חיים וחיסכון ארוך טווח: ביטוח חיים',
  'Health Insurance - Health Insurance - other: Medical expenses and disabilities - individual': 'בריאות, אחר: הוצאות רפואיות ונכויות, פרט',
  'Health Insurance - Health Insurance - other: Medical expenses and disabilities - collective (incl. dental)': 'בריאות, אחר: הוצאות רפואיות ונכויות, קולקטיב (כולל שיניים)',
  'Health Insurance - Health Insurance - other: Other (critical illness, foreign workers, travel, personal accidents)': 'בריאות, אחר: אחר (מחלות קשות, עובדים זרים, נסיעות לחו"ל, תאונות אישיות)',
  'Health Insurance - LTC - Individual': 'בריאות: סיעוד, פרט', 'Health Insurance - LTC - Collective': 'בריאות: סיעוד, קולקטיב',
  wesure: 'ווישור', 'P&C Insurance - Other': 'ביטוח כללי: אחר', 'P&C Insurance - Compulsory Motor': 'ביטוח כללי: רכב חובה', 'P&C Insurance - Motor Property': 'ביטוח כללי: רכב רכוש',
  Retirement: 'פרישה', 'Retirement - Provident': 'פרישה: גמל', 'Retirement - Pension': 'פרישה: פנסיה', agencies: 'סוכנויות', adjustments_eliminations: 'התאמות וקיזוזים',
  group_growth_products: 'קבוצה: מוצרי צמיחה', growth_products: 'מוצרי צמיחה', 'Long-Term Savings - investment contracts': 'חיסכון ארוך טווח: פוליסות חיסכון (חוזי השקעה)', 'Life Insurance': 'ביטוח חיים',
  'פוליסות הכוללות רכיב חיסכון תלוי תשואה': 'פוליסות הכוללות רכיב חיסכון תלוי תשואה (ביטוחי מנהלים)', 'פוליסות ללא רכיב חיסכון': 'פוליסות ללא רכיב חיסכון',
  'פוליסות הכוללות רכיב חיסכון שאינו תלוי תשואה': 'פוליסות הכוללות רכיב חיסכון שאינו תלוי תשואה (ביטוחי מנהלים)',
  'Brokers & Advisors': 'סוכנים ויועצים', 'Payments & Financing': 'תשלומים ומימון', group_run_off: 'קבוצה: ראן-אוף', not_attributed: 'לא מיוחס', 'investment contracts': 'פוליסות חיסכון (חוזי השקעה)',
  growth_products_life: 'מוצרי צמיחה: חיים', growth_products_health: 'מוצרי צמיחה: בריאות', life_health_combined: 'חיים ובריאות', clal_insurance_subsidiary: 'כלל ביטוח',
  long_term_savings: 'חיסכון ארוך טווח', 'Other (non-segmented)': 'אחר (לא מיוחס למגזרים)', 'non-controlling interests': 'זכויות שאינן מקנות שליטה', 'Insurance Agencies': 'סוכנויות ביטוח',
  life_incl_investment_contracts: 'חיים כולל פוליסות חיסכון (חוזי השקעה)', group_incl_nostro: 'קבוצה כולל נוסטרו', 'group (including nostro)': 'קבוצה (כולל נוסטרו)', 'group (policyholders and planholders)': 'קבוצה (מבוטחים וחברי תוכניות)',
  life_growth_products: 'חיים: מוצרי צמיחה', health_growth_products: 'בריאות: מוצרי צמיחה', phoenix_insurance_mcr: 'הפניקס ביטוח, MCR', credit_insurance: 'ביטוח אשראי', insurance_and_savings: 'ביטוח וחיסכון',
  agencies_and_other: 'סוכנויות ואחר', not_allocated: 'לא מיוחס', other_operating_segments: 'מגזרי פעילות אחרים', mutual_funds: 'קרנות נאמנות', members_and_insureds_total: 'סך חברים ומבוטחים',
  asset_management_total: 'סך ניהול נכסים', 'Pension and Provident Subsegments': 'תתי מגזרי פנסיה וגמל', 'HMO long-term-care funds operation and others': 'הפעלת קרנות סיעוד של קופות החולים ואחרים',
  'פעילות שירותים פיננסיים': 'פעילות שירותים פיננסיים', 'מגזרי פעילות אחרים': 'מגזרי פעילות אחרים', 'פעילות שאינה מיוחסת למגזרי פעילות': 'פעילות שאינה מיוחסת למגזרי פעילות',
  'remaining operating segments': 'יתר מגזרי הפעילות', 'Pension and Provident': 'פנסיה וגמל', run_off_products: 'מוצרי ראן-אוף',
};

export const BUCKET_HE: Record<string, string> = {
  'up to 1 year': 'עד שנה', '1-2 years': '1 עד 2 שנים', '2-3 years': '2 עד 3 שנים', '3-4 years': '3 עד 4 שנים', '4-5 years': '4 עד 5 שנים', '5-10 years': '5 עד 10 שנים',
  '10-15 years': '10 עד 15 שנים', 'over 15 years': 'מעל 15 שנים', '1 year': 'שנה', '3 years': '3 שנים', '5 years': '5 שנים', '10 years': '10 שנים', '15 years': '15 שנים', '25 years': '25 שנים',
  '35 years': '35 שנים', '45 years': '45 שנים', '60 years': '60 שנים', 'total carrying value': 'סך ערך בספרים', 'Total - carrying value': 'סך ערך בספרים', total: 'סך הכול',
  'Up to one year': 'עד שנה', 'From one year to 2 years': 'משנה עד 2 שנים', 'From 2 to 3 years': '2 עד 3 שנים', 'From 3 to 4 years': '3 עד 4 שנים', 'From 4 to 5 years': '4 עד 5 שנים',
  'From 5 to 10 years': '5 עד 10 שנים', 'From 10 to 15 years': '10 עד 15 שנים', 'More than 15 years': 'מעל 15 שנים', 'over 2040': 'מעל 2040',
};

export const EFFECT_HE: Record<string, string> = {
  csm: 'CSM', CSM: 'CSM', 'CSM balance': 'יתרת CSM', profit_after_tax: 'רווח לאחר מס', equity_after_tax: 'הון לאחר מס', profit_or_loss: 'רווח או הפסד',
  profit_and_equity_after_tax: 'רווח והון לאחר מס', 'equity (after tax)': 'הון (לאחר מס)', 'profit or loss (after tax)': 'רווח או הפסד (לאחר מס)', investment_and_finance_result: 'תוצאות השקעה ומימון',
  'income (loss) from investments and finance, net': 'הכנסות (הפסדים) מהשקעות ומימון, נטו', insurance_service_result: 'תוצאות שירותי ביטוח', 'income from insurance services': 'הכנסות משירותי ביטוח',
  comprehensive_income: 'רווח כולל', profit_before_tax: 'רווח לפני מס', oci: 'רווח כולל אחר',
};
